baseurl = "https://ykth.github.io/blog/"
title = "yk.th Blog"
theme = "hugo-creative-portfolio-theme"
languageCode = "ja-jp"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "default"
  description = "Describe your website"
  copyright = "&copy;2020 Yuki Takahashi"
    # Optional Matomo analytics (formerly piwik)
      # [params.analytics.matomo]
      #  URL = "https://stats.example.com"
      #  ID = "42"
      #  # Track all subdomains with "*.example.com" (Optional)
      #  domain = "www.example.com"
      #  # Optional integrity check hash
      #  hash = ""

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "posts/"
  home = true

  [[params.navlinks]]
  name = "Profile"
  url = "profile/"

  [params.social]
  instagram     = "https://www.instagram.com/yk.th"
